/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the MachineUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MachineUpdateRequest{}

// MachineUpdateRequest Request data to update Machine. Instance Type attribute updates, maintenance attribute updates, labels updates, and in-pool online repair (enter or exit) must be specified in separate requests. They cannot be processed at the same time.
type MachineUpdateRequest struct {
	// Update the Instance Type of the Machine. Cannot be specified when clearing Instance Type. Can only be updated by Provider.
	InstanceTypeId NullableString `json:"instanceTypeId,omitempty"`
	// Set to true to clear the existing Instance Type. Cannot be specified if Instance Type ID is specified. Can only be set by Provider.
	ClearInstanceType NullableBool `json:"clearInstanceType,omitempty"`
	// Set to `true` to enable maintenance mode and to `false` to disable maintenance mode. Can be set by Provider or Privileged Tenant.
	SetMaintenanceMode NullableBool `json:"setMaintenanceMode,omitempty"`
	// Optional message describing the reason for moving Machine into maintenance mode. Can be updated by Provider or Privileged Tenant.
	MaintenanceMessage NullableString    `json:"maintenanceMessage,omitempty"`
	Labels             map[string]string `json:"labels,omitempty"`
	// When true, initiates in-pool online repair: applies the tenant-reported OnlineRepair health override on the machine and sets the associated Instance status to Repairing. When false, must be used with clearOnlineRepair true to exit online repair. Cannot be combined with instance type, maintenance, or label updates in the same request. When `requestOnlineRepair` is true, `machineHealthIssue`, `repairPolicy`, and `acknowledgments` are required in the same request body and must satisfy the `MachineHealthIssue`, `OnlineRepairPolicy`, and `OnlineRepairAcknowledgments` component schemas.
	RequestOnlineRepair NullableBool `json:"requestOnlineRepair,omitempty"`
	// Must be true when requestOnlineRepair is false. Clears the OnlineRepair health override and returns the Instance to Ready.
	ClearOnlineRepair  NullableBool                 `json:"clearOnlineRepair,omitempty"`
	MachineHealthIssue *MachineHealthIssue          `json:"machineHealthIssue,omitempty"`
	RepairPolicy       *OnlineRepairPolicy          `json:"repairPolicy,omitempty"`
	Acknowledgments    *OnlineRepairAcknowledgments `json:"acknowledgments,omitempty"`
}

// NewMachineUpdateRequest instantiates a new MachineUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachineUpdateRequest() *MachineUpdateRequest {
	this := MachineUpdateRequest{}
	return &this
}

// NewMachineUpdateRequestWithDefaults instantiates a new MachineUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachineUpdateRequestWithDefaults() *MachineUpdateRequest {
	this := MachineUpdateRequest{}
	return &this
}

// GetInstanceTypeId returns the InstanceTypeId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineUpdateRequest) GetInstanceTypeId() string {
	if o == nil || IsNil(o.InstanceTypeId.Get()) {
		var ret string
		return ret
	}
	return *o.InstanceTypeId.Get()
}

// GetInstanceTypeIdOk returns a tuple with the InstanceTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineUpdateRequest) GetInstanceTypeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InstanceTypeId.Get(), o.InstanceTypeId.IsSet()
}

// HasInstanceTypeId returns a boolean if a field has been set.
func (o *MachineUpdateRequest) HasInstanceTypeId() bool {
	if o != nil && o.InstanceTypeId.IsSet() {
		return true
	}

	return false
}

// SetInstanceTypeId gets a reference to the given NullableString and assigns it to the InstanceTypeId field.
func (o *MachineUpdateRequest) SetInstanceTypeId(v string) {
	o.InstanceTypeId.Set(&v)
}

// SetInstanceTypeIdNil sets the value for InstanceTypeId to be an explicit nil
func (o *MachineUpdateRequest) SetInstanceTypeIdNil() {
	o.InstanceTypeId.Set(nil)
}

// UnsetInstanceTypeId ensures that no value is present for InstanceTypeId, not even an explicit nil
func (o *MachineUpdateRequest) UnsetInstanceTypeId() {
	o.InstanceTypeId.Unset()
}

// GetClearInstanceType returns the ClearInstanceType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineUpdateRequest) GetClearInstanceType() bool {
	if o == nil || IsNil(o.ClearInstanceType.Get()) {
		var ret bool
		return ret
	}
	return *o.ClearInstanceType.Get()
}

// GetClearInstanceTypeOk returns a tuple with the ClearInstanceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineUpdateRequest) GetClearInstanceTypeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClearInstanceType.Get(), o.ClearInstanceType.IsSet()
}

// HasClearInstanceType returns a boolean if a field has been set.
func (o *MachineUpdateRequest) HasClearInstanceType() bool {
	if o != nil && o.ClearInstanceType.IsSet() {
		return true
	}

	return false
}

// SetClearInstanceType gets a reference to the given NullableBool and assigns it to the ClearInstanceType field.
func (o *MachineUpdateRequest) SetClearInstanceType(v bool) {
	o.ClearInstanceType.Set(&v)
}

// SetClearInstanceTypeNil sets the value for ClearInstanceType to be an explicit nil
func (o *MachineUpdateRequest) SetClearInstanceTypeNil() {
	o.ClearInstanceType.Set(nil)
}

// UnsetClearInstanceType ensures that no value is present for ClearInstanceType, not even an explicit nil
func (o *MachineUpdateRequest) UnsetClearInstanceType() {
	o.ClearInstanceType.Unset()
}

// GetSetMaintenanceMode returns the SetMaintenanceMode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineUpdateRequest) GetSetMaintenanceMode() bool {
	if o == nil || IsNil(o.SetMaintenanceMode.Get()) {
		var ret bool
		return ret
	}
	return *o.SetMaintenanceMode.Get()
}

// GetSetMaintenanceModeOk returns a tuple with the SetMaintenanceMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineUpdateRequest) GetSetMaintenanceModeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SetMaintenanceMode.Get(), o.SetMaintenanceMode.IsSet()
}

// HasSetMaintenanceMode returns a boolean if a field has been set.
func (o *MachineUpdateRequest) HasSetMaintenanceMode() bool {
	if o != nil && o.SetMaintenanceMode.IsSet() {
		return true
	}

	return false
}

// SetSetMaintenanceMode gets a reference to the given NullableBool and assigns it to the SetMaintenanceMode field.
func (o *MachineUpdateRequest) SetSetMaintenanceMode(v bool) {
	o.SetMaintenanceMode.Set(&v)
}

// SetSetMaintenanceModeNil sets the value for SetMaintenanceMode to be an explicit nil
func (o *MachineUpdateRequest) SetSetMaintenanceModeNil() {
	o.SetMaintenanceMode.Set(nil)
}

// UnsetSetMaintenanceMode ensures that no value is present for SetMaintenanceMode, not even an explicit nil
func (o *MachineUpdateRequest) UnsetSetMaintenanceMode() {
	o.SetMaintenanceMode.Unset()
}

// GetMaintenanceMessage returns the MaintenanceMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineUpdateRequest) GetMaintenanceMessage() string {
	if o == nil || IsNil(o.MaintenanceMessage.Get()) {
		var ret string
		return ret
	}
	return *o.MaintenanceMessage.Get()
}

// GetMaintenanceMessageOk returns a tuple with the MaintenanceMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineUpdateRequest) GetMaintenanceMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaintenanceMessage.Get(), o.MaintenanceMessage.IsSet()
}

// HasMaintenanceMessage returns a boolean if a field has been set.
func (o *MachineUpdateRequest) HasMaintenanceMessage() bool {
	if o != nil && o.MaintenanceMessage.IsSet() {
		return true
	}

	return false
}

// SetMaintenanceMessage gets a reference to the given NullableString and assigns it to the MaintenanceMessage field.
func (o *MachineUpdateRequest) SetMaintenanceMessage(v string) {
	o.MaintenanceMessage.Set(&v)
}

// SetMaintenanceMessageNil sets the value for MaintenanceMessage to be an explicit nil
func (o *MachineUpdateRequest) SetMaintenanceMessageNil() {
	o.MaintenanceMessage.Set(nil)
}

// UnsetMaintenanceMessage ensures that no value is present for MaintenanceMessage, not even an explicit nil
func (o *MachineUpdateRequest) UnsetMaintenanceMessage() {
	o.MaintenanceMessage.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *MachineUpdateRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineUpdateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *MachineUpdateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *MachineUpdateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetRequestOnlineRepair returns the RequestOnlineRepair field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineUpdateRequest) GetRequestOnlineRepair() bool {
	if o == nil || IsNil(o.RequestOnlineRepair.Get()) {
		var ret bool
		return ret
	}
	return *o.RequestOnlineRepair.Get()
}

// GetRequestOnlineRepairOk returns a tuple with the RequestOnlineRepair field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineUpdateRequest) GetRequestOnlineRepairOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequestOnlineRepair.Get(), o.RequestOnlineRepair.IsSet()
}

// HasRequestOnlineRepair returns a boolean if a field has been set.
func (o *MachineUpdateRequest) HasRequestOnlineRepair() bool {
	if o != nil && o.RequestOnlineRepair.IsSet() {
		return true
	}

	return false
}

// SetRequestOnlineRepair gets a reference to the given NullableBool and assigns it to the RequestOnlineRepair field.
func (o *MachineUpdateRequest) SetRequestOnlineRepair(v bool) {
	o.RequestOnlineRepair.Set(&v)
}

// SetRequestOnlineRepairNil sets the value for RequestOnlineRepair to be an explicit nil
func (o *MachineUpdateRequest) SetRequestOnlineRepairNil() {
	o.RequestOnlineRepair.Set(nil)
}

// UnsetRequestOnlineRepair ensures that no value is present for RequestOnlineRepair, not even an explicit nil
func (o *MachineUpdateRequest) UnsetRequestOnlineRepair() {
	o.RequestOnlineRepair.Unset()
}

// GetClearOnlineRepair returns the ClearOnlineRepair field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineUpdateRequest) GetClearOnlineRepair() bool {
	if o == nil || IsNil(o.ClearOnlineRepair.Get()) {
		var ret bool
		return ret
	}
	return *o.ClearOnlineRepair.Get()
}

// GetClearOnlineRepairOk returns a tuple with the ClearOnlineRepair field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineUpdateRequest) GetClearOnlineRepairOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClearOnlineRepair.Get(), o.ClearOnlineRepair.IsSet()
}

// HasClearOnlineRepair returns a boolean if a field has been set.
func (o *MachineUpdateRequest) HasClearOnlineRepair() bool {
	if o != nil && o.ClearOnlineRepair.IsSet() {
		return true
	}

	return false
}

// SetClearOnlineRepair gets a reference to the given NullableBool and assigns it to the ClearOnlineRepair field.
func (o *MachineUpdateRequest) SetClearOnlineRepair(v bool) {
	o.ClearOnlineRepair.Set(&v)
}

// SetClearOnlineRepairNil sets the value for ClearOnlineRepair to be an explicit nil
func (o *MachineUpdateRequest) SetClearOnlineRepairNil() {
	o.ClearOnlineRepair.Set(nil)
}

// UnsetClearOnlineRepair ensures that no value is present for ClearOnlineRepair, not even an explicit nil
func (o *MachineUpdateRequest) UnsetClearOnlineRepair() {
	o.ClearOnlineRepair.Unset()
}

// GetMachineHealthIssue returns the MachineHealthIssue field value if set, zero value otherwise.
func (o *MachineUpdateRequest) GetMachineHealthIssue() MachineHealthIssue {
	if o == nil || IsNil(o.MachineHealthIssue) {
		var ret MachineHealthIssue
		return ret
	}
	return *o.MachineHealthIssue
}

// GetMachineHealthIssueOk returns a tuple with the MachineHealthIssue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineUpdateRequest) GetMachineHealthIssueOk() (*MachineHealthIssue, bool) {
	if o == nil || IsNil(o.MachineHealthIssue) {
		return nil, false
	}
	return o.MachineHealthIssue, true
}

// HasMachineHealthIssue returns a boolean if a field has been set.
func (o *MachineUpdateRequest) HasMachineHealthIssue() bool {
	if o != nil && !IsNil(o.MachineHealthIssue) {
		return true
	}

	return false
}

// SetMachineHealthIssue gets a reference to the given MachineHealthIssue and assigns it to the MachineHealthIssue field.
func (o *MachineUpdateRequest) SetMachineHealthIssue(v MachineHealthIssue) {
	o.MachineHealthIssue = &v
}

// GetRepairPolicy returns the RepairPolicy field value if set, zero value otherwise.
func (o *MachineUpdateRequest) GetRepairPolicy() OnlineRepairPolicy {
	if o == nil || IsNil(o.RepairPolicy) {
		var ret OnlineRepairPolicy
		return ret
	}
	return *o.RepairPolicy
}

// GetRepairPolicyOk returns a tuple with the RepairPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineUpdateRequest) GetRepairPolicyOk() (*OnlineRepairPolicy, bool) {
	if o == nil || IsNil(o.RepairPolicy) {
		return nil, false
	}
	return o.RepairPolicy, true
}

// HasRepairPolicy returns a boolean if a field has been set.
func (o *MachineUpdateRequest) HasRepairPolicy() bool {
	if o != nil && !IsNil(o.RepairPolicy) {
		return true
	}

	return false
}

// SetRepairPolicy gets a reference to the given OnlineRepairPolicy and assigns it to the RepairPolicy field.
func (o *MachineUpdateRequest) SetRepairPolicy(v OnlineRepairPolicy) {
	o.RepairPolicy = &v
}

// GetAcknowledgments returns the Acknowledgments field value if set, zero value otherwise.
func (o *MachineUpdateRequest) GetAcknowledgments() OnlineRepairAcknowledgments {
	if o == nil || IsNil(o.Acknowledgments) {
		var ret OnlineRepairAcknowledgments
		return ret
	}
	return *o.Acknowledgments
}

// GetAcknowledgmentsOk returns a tuple with the Acknowledgments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineUpdateRequest) GetAcknowledgmentsOk() (*OnlineRepairAcknowledgments, bool) {
	if o == nil || IsNil(o.Acknowledgments) {
		return nil, false
	}
	return o.Acknowledgments, true
}

// HasAcknowledgments returns a boolean if a field has been set.
func (o *MachineUpdateRequest) HasAcknowledgments() bool {
	if o != nil && !IsNil(o.Acknowledgments) {
		return true
	}

	return false
}

// SetAcknowledgments gets a reference to the given OnlineRepairAcknowledgments and assigns it to the Acknowledgments field.
func (o *MachineUpdateRequest) SetAcknowledgments(v OnlineRepairAcknowledgments) {
	o.Acknowledgments = &v
}

func (o MachineUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MachineUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.InstanceTypeId.IsSet() {
		toSerialize["instanceTypeId"] = o.InstanceTypeId.Get()
	}
	if o.ClearInstanceType.IsSet() {
		toSerialize["clearInstanceType"] = o.ClearInstanceType.Get()
	}
	if o.SetMaintenanceMode.IsSet() {
		toSerialize["setMaintenanceMode"] = o.SetMaintenanceMode.Get()
	}
	if o.MaintenanceMessage.IsSet() {
		toSerialize["maintenanceMessage"] = o.MaintenanceMessage.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if o.RequestOnlineRepair.IsSet() {
		toSerialize["requestOnlineRepair"] = o.RequestOnlineRepair.Get()
	}
	if o.ClearOnlineRepair.IsSet() {
		toSerialize["clearOnlineRepair"] = o.ClearOnlineRepair.Get()
	}
	if !IsNil(o.MachineHealthIssue) {
		toSerialize["machineHealthIssue"] = o.MachineHealthIssue
	}
	if !IsNil(o.RepairPolicy) {
		toSerialize["repairPolicy"] = o.RepairPolicy
	}
	if !IsNil(o.Acknowledgments) {
		toSerialize["acknowledgments"] = o.Acknowledgments
	}
	return toSerialize, nil
}

type NullableMachineUpdateRequest struct {
	value *MachineUpdateRequest
	isSet bool
}

func (v NullableMachineUpdateRequest) Get() *MachineUpdateRequest {
	return v.value
}

func (v *NullableMachineUpdateRequest) Set(val *MachineUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMachineUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMachineUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachineUpdateRequest(val *MachineUpdateRequest) *NullableMachineUpdateRequest {
	return &NullableMachineUpdateRequest{value: val, isSet: true}
}

func (v NullableMachineUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachineUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
