/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TenantCapabilityUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantCapabilityUpdateRequest{}

// TenantCapabilityUpdateRequest Request data to enable or disable a scoped Tenant capability for a resolved set of Sites.  An empty `sites` array applies the change to all eligible Sites (optionally filtered by `infrastructureProviderId`); a non-empty array scopes the change to the listed Sites.
type TenantCapabilityUpdateRequest struct {
	// The capability to toggle
	CapabilityName string `json:"capabilityName"`
	// Site IDs to scope the change to. Empty array means all eligible Sites.
	Sites []string `json:"sites,omitempty"`
	// Optionally restrict the resolved Site set to Sites owned by this provider
	InfrastructureProviderId *string `json:"infrastructureProviderId,omitempty"`
	// true opts in, false opts out, for the resolved Sites
	Enabled bool `json:"enabled"`
}

type _TenantCapabilityUpdateRequest TenantCapabilityUpdateRequest

// NewTenantCapabilityUpdateRequest instantiates a new TenantCapabilityUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantCapabilityUpdateRequest(capabilityName string, enabled bool) *TenantCapabilityUpdateRequest {
	this := TenantCapabilityUpdateRequest{}
	this.CapabilityName = capabilityName
	this.Enabled = enabled
	return &this
}

// NewTenantCapabilityUpdateRequestWithDefaults instantiates a new TenantCapabilityUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantCapabilityUpdateRequestWithDefaults() *TenantCapabilityUpdateRequest {
	this := TenantCapabilityUpdateRequest{}
	return &this
}

// GetCapabilityName returns the CapabilityName field value
func (o *TenantCapabilityUpdateRequest) GetCapabilityName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CapabilityName
}

// GetCapabilityNameOk returns a tuple with the CapabilityName field value
// and a boolean to check if the value has been set.
func (o *TenantCapabilityUpdateRequest) GetCapabilityNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CapabilityName, true
}

// SetCapabilityName sets field value
func (o *TenantCapabilityUpdateRequest) SetCapabilityName(v string) {
	o.CapabilityName = v
}

// GetSites returns the Sites field value if set, zero value otherwise.
func (o *TenantCapabilityUpdateRequest) GetSites() []string {
	if o == nil || IsNil(o.Sites) {
		var ret []string
		return ret
	}
	return o.Sites
}

// GetSitesOk returns a tuple with the Sites field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantCapabilityUpdateRequest) GetSitesOk() ([]string, bool) {
	if o == nil || IsNil(o.Sites) {
		return nil, false
	}
	return o.Sites, true
}

// HasSites returns a boolean if a field has been set.
func (o *TenantCapabilityUpdateRequest) HasSites() bool {
	if o != nil && !IsNil(o.Sites) {
		return true
	}

	return false
}

// SetSites gets a reference to the given []string and assigns it to the Sites field.
func (o *TenantCapabilityUpdateRequest) SetSites(v []string) {
	o.Sites = v
}

// GetInfrastructureProviderId returns the InfrastructureProviderId field value if set, zero value otherwise.
func (o *TenantCapabilityUpdateRequest) GetInfrastructureProviderId() string {
	if o == nil || IsNil(o.InfrastructureProviderId) {
		var ret string
		return ret
	}
	return *o.InfrastructureProviderId
}

// GetInfrastructureProviderIdOk returns a tuple with the InfrastructureProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantCapabilityUpdateRequest) GetInfrastructureProviderIdOk() (*string, bool) {
	if o == nil || IsNil(o.InfrastructureProviderId) {
		return nil, false
	}
	return o.InfrastructureProviderId, true
}

// HasInfrastructureProviderId returns a boolean if a field has been set.
func (o *TenantCapabilityUpdateRequest) HasInfrastructureProviderId() bool {
	if o != nil && !IsNil(o.InfrastructureProviderId) {
		return true
	}

	return false
}

// SetInfrastructureProviderId gets a reference to the given string and assigns it to the InfrastructureProviderId field.
func (o *TenantCapabilityUpdateRequest) SetInfrastructureProviderId(v string) {
	o.InfrastructureProviderId = &v
}

// GetEnabled returns the Enabled field value
func (o *TenantCapabilityUpdateRequest) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *TenantCapabilityUpdateRequest) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *TenantCapabilityUpdateRequest) SetEnabled(v bool) {
	o.Enabled = v
}

func (o TenantCapabilityUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantCapabilityUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["capabilityName"] = o.CapabilityName
	if !IsNil(o.Sites) {
		toSerialize["sites"] = o.Sites
	}
	if !IsNil(o.InfrastructureProviderId) {
		toSerialize["infrastructureProviderId"] = o.InfrastructureProviderId
	}
	toSerialize["enabled"] = o.Enabled
	return toSerialize, nil
}

func (o *TenantCapabilityUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"capabilityName",
		"enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenantCapabilityUpdateRequest := _TenantCapabilityUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTenantCapabilityUpdateRequest)

	if err != nil {
		return err
	}

	*o = TenantCapabilityUpdateRequest(varTenantCapabilityUpdateRequest)

	return err
}

type NullableTenantCapabilityUpdateRequest struct {
	value *TenantCapabilityUpdateRequest
	isSet bool
}

func (v NullableTenantCapabilityUpdateRequest) Get() *TenantCapabilityUpdateRequest {
	return v.value
}

func (v *NullableTenantCapabilityUpdateRequest) Set(val *TenantCapabilityUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantCapabilityUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantCapabilityUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantCapabilityUpdateRequest(val *TenantCapabilityUpdateRequest) *NullableTenantCapabilityUpdateRequest {
	return &NullableTenantCapabilityUpdateRequest{value: val, isSet: true}
}

func (v NullableTenantCapabilityUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantCapabilityUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
