/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the TenantCapability type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantCapability{}

// TenantCapability Result of a scoped Tenant capability update
type TenantCapability struct {
	CapabilityName *string  `json:"capabilityName,omitempty"`
	Enabled        *bool    `json:"enabled,omitempty"`
	SiteIds        []string `json:"siteIds,omitempty"`
}

// NewTenantCapability instantiates a new TenantCapability object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantCapability() *TenantCapability {
	this := TenantCapability{}
	return &this
}

// NewTenantCapabilityWithDefaults instantiates a new TenantCapability object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantCapabilityWithDefaults() *TenantCapability {
	this := TenantCapability{}
	return &this
}

// GetCapabilityName returns the CapabilityName field value if set, zero value otherwise.
func (o *TenantCapability) GetCapabilityName() string {
	if o == nil || IsNil(o.CapabilityName) {
		var ret string
		return ret
	}
	return *o.CapabilityName
}

// GetCapabilityNameOk returns a tuple with the CapabilityName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantCapability) GetCapabilityNameOk() (*string, bool) {
	if o == nil || IsNil(o.CapabilityName) {
		return nil, false
	}
	return o.CapabilityName, true
}

// HasCapabilityName returns a boolean if a field has been set.
func (o *TenantCapability) HasCapabilityName() bool {
	if o != nil && !IsNil(o.CapabilityName) {
		return true
	}

	return false
}

// SetCapabilityName gets a reference to the given string and assigns it to the CapabilityName field.
func (o *TenantCapability) SetCapabilityName(v string) {
	o.CapabilityName = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *TenantCapability) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantCapability) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *TenantCapability) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *TenantCapability) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetSiteIds returns the SiteIds field value if set, zero value otherwise.
func (o *TenantCapability) GetSiteIds() []string {
	if o == nil || IsNil(o.SiteIds) {
		var ret []string
		return ret
	}
	return o.SiteIds
}

// GetSiteIdsOk returns a tuple with the SiteIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantCapability) GetSiteIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SiteIds) {
		return nil, false
	}
	return o.SiteIds, true
}

// HasSiteIds returns a boolean if a field has been set.
func (o *TenantCapability) HasSiteIds() bool {
	if o != nil && !IsNil(o.SiteIds) {
		return true
	}

	return false
}

// SetSiteIds gets a reference to the given []string and assigns it to the SiteIds field.
func (o *TenantCapability) SetSiteIds(v []string) {
	o.SiteIds = v
}

func (o TenantCapability) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantCapability) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CapabilityName) {
		toSerialize["capabilityName"] = o.CapabilityName
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.SiteIds) {
		toSerialize["siteIds"] = o.SiteIds
	}
	return toSerialize, nil
}

type NullableTenantCapability struct {
	value *TenantCapability
	isSet bool
}

func (v NullableTenantCapability) Get() *TenantCapability {
	return v.value
}

func (v *NullableTenantCapability) Set(val *TenantCapability) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantCapability) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantCapability) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantCapability(val *TenantCapability) *NullableTenantCapability {
	return &NullableTenantCapability{value: val, isSet: true}
}

func (v NullableTenantCapability) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantCapability) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
